version: '3.2'
services:
  mk.demo.gateway:
    image: mk.demo.gateway.img
    build:
      context: .
      dockerfile: ./Gateways/Mk.Demo.Gateway/Dockerfile
    ports:
      - target: 44502                    
        published: 44502              
        protocol: tcp                 
        mode: host  
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:44502
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - type: bind
        source: /usr/local/app-data/logs/Mk.Demo.Gateway
        target: /app/Logs
      - type: bind
        source: /usr/local/app-data/config/Mk.Demo.Gateway/appsettings.Production.json
        target: /app/appsettings.Production.json
      - type: bind
        source: /usr/local/app-data/config/Mk.Demo.Gateway/ocelot.Production.json
        target: /app/ocelot.Production.json
    container_name: mk.demo.gateway
    networks:
      - my-net

  mk.demob.api:
    image: mk.demob.api.img
    build:
      context: .
      dockerfile: ./Mk.DemoB/src/Mk.DemoB.HttpApi.Host/Dockerfile
    ports:
      - target: 44302                    
        published: 44302              
        protocol: tcp                 
        mode: host  
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:44302
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - type: bind
        source: /usr/local/app-data/logs/Mk.DemoB.Api
        target: /app/Logs
      - type: bind
        source: /usr/local/app-data/config/Mk.DemoB.Api/appsettings.Production.json
        target: /app/appsettings.Production.json
    networks:
      - my-net
    container_name: mk.demob.api
    depends_on:
      - mk.demo.gateway
      - mk.democ.api

  mk.democ.api:
    image: mk.democ.api.img
    build:
      context: .
      dockerfile: ./Mk.DemoC/src/Mk.DemoC.HttpApi.Host/Dockerfile
    ports:
      - target: 44402                    
        published: 44402              
        protocol: tcp                 
        mode: host  
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:44402
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - type: bind
        source: /usr/local/app-data/logs/Mk.DemoC.Api
        target: /app/Logs
      - type: bind
        source: /usr/local/app-data/config/Mk.DemoC.Api/appsettings.Production.json
        target: /app/appsettings.Production.json
    networks:
      - my-net
    container_name: mk.democ.api
    depends_on:
      - mk.demo.gateway

networks:
  my-net:
    driver: bridge